export const PROPERTIES = [
  {
    propId: 1,
    tag: "highland-park1",
    title: "Highland Park Rambler",
    neighborhood: "Highland Park, Seattle",
    address: "8118 15th Ave SW, Seattle, WA 98106",
    description: "Our first project, purchased at foreclosure auction",
    imgPostUrl: "./images/highland-park1/01-post.jpg",
    imgB4Url: "./images/highland-park1/01-b4.jpg",
    mapCoord: "300,660",
    purchaseDate: "Aug-2014",
    purchasePrice: 190446,
    saleDate: "Jan-2015",
    salePrice: 320000
  },
  {
    propId: 2,
    tag: "halls-lake",
    title: "Halls Lake Midcentury",
    neighborhood: "Halls Lake, Lynnwood",
    address: "5804 202nd St SW, Lynnwood, WA 98036",
    description: "Mid century style, detached garage bonus / median room",
    imgPostUrl: "./images/halls-lake/01-post.jpg",
    imgB4Url: "./images/halls-lake/01-b4.jpg",
    mapCoord: "357,38",
    purchaseDate: "Feb-2015",
    purchasePrice: 195539,
    saleDate: "May-2015",
    salePrice: 291500
  },
  {
    propId: 3,
    tag: "lakeview",
    title: "Cottage Lake View Treehouse",
    neighborhood: "Cottage Lake, Woodinville",
    address: "17701 185th Ave NE Woodinville, WA 98072",
    description:
      "Unique architecture, treehouse feel, beautiful view of Cottage Lake",
    imgPostUrl: "./images/lakeview/01-post.jpg",
    imgB4Url: "./images/lakeview/01-b4.jpg",
    mapCoord: "675,166",
    purchaseDate: "Jul-2015",
    purchasePrice: 271363,
    saleDate: "Feb-2016",
    salePrice: 430000
  },
  {
    propId: 4,
    tag: "rolling-hills",
    title: "Rolling Hills Condo",
    neighborhood: "Rolling Hills, Renton",
    address: "2020 Grant Ave S Unit F201 Renton, WA 98055",
    description:
      "Purchased from the condo HOA at sheriff auction; rented for some time before we sold it",
    imgPostUrl: "./images/rolling-hills/01-post.jpg",
    imgB4Url: "./images/rolling-hills/01-b4.jpg",
    mapCoord: "521,800",
    purchaseDate: "Sep-2014",
    purchasePrice: 81694,
    saleDate: "42491",
    salePrice: 170000
  },
  {
    propId: 5,
    tag: "highland-park2",
    title: "Highland Park Cape Cod",
    neighborhood: "Highland Park, Seattle",
    address: "7938 20th Ave SW, Seattle, WA 98106",
    description: "Charming classic with character-filled upper story",
    imgPostUrl: "./images/highland-park2/01-post.jpg",
    imgB4Url: "./images/highland-park2/01-b4.jpg",
    mapCoord: "284,652",
    purchaseDate: "Aug-2016",
    purchasePrice: 319276,
    saleDate: "Jan-2017",
    salePrice: 499000
  },
  {
    propId: 6,
    tag: "matthews-beach",
    title: "Matthews Beach Bungalow",
    neighborhood: "Matthews Beach, Seattle",
    address: "11332 36th Ave NE, Seattle, WA 98125",
    description:
      "One-story living, detached 2-car garage, quiet neighborhood near Thornton Creek",
    imgPostUrl: "./images/matthews-beach/01-post.jpg",
    imgB4Url: "./images/matthews-beach/01-b4.jpg",
    mapCoord: "390,262",
    purchaseDate: "Sep-2016",
    purchasePrice: 387372,
    saleDate: "Mar-2017",
    salePrice: 675000
  },
  {
    propId: 7,
    tag: "broadview2",
    title: "Broadview One-and-a-half Story Brick Classic",
    neighborhood: "Broadview, Seattle",
    address: "104 NW 137th St, Seattle, WA 98177",
    description: "Cute attic, converted garage space, awesome yard",
    imgPostUrl: "./images/broadview2/01-post.jpg",
    imgB4Url: "./images/broadview2/01-b4.jpg",
    mapCoord: "289,225",
    purchaseDate: "Mar-2017",
    purchasePrice: 467664,
    saleDate: "Aug-2017",
    salePrice: 665000
  },
  {
    propId: 8,
    tag: "arrowhead",
    title: "Arrowhead Split-Level",
    neighborhood: "Arrowhead, Kenmore",
    address: "7216 NE 150th St, Kenmore, WA 98028",
    description: "Private split-level with open floor plan and large deck",
    imgPostUrl: "./images/arrowhead/01-post.jpg",
    imgB4Url: "./images/arrowhead/01-b4.jpg",
    mapCoord: "453,205",
    purchaseDate: "Jun-2017",
    purchasePrice: 431187,
    saleDate: "Sep-2017",
    salePrice: 590000
  },
  {
    propId: 9,
    tag: "magnolia",
    title: "Magnolia View Tudor",
    neighborhood: "Magnolila, Seattle",
    address: "2606 W Boston St, Seattle, WA 98199",
    description: "3 story floor plan that makes sense with amazing views",
    imgPostUrl: "./images/magnolia/01-post.jpg",
    imgB4Url: "./images/magnolia/01-b4.jpg",
    mapCoord: "241,419",
    purchaseDate: "Mar-2017",
    purchasePrice: 803630,
    saleDate: "Oct-2018",
    salePrice: 1390000
  },
  {
    propId: 10,
    tag: "queen-anne2",
    title: "Queen Anne Classic Charmer",
    neighborhood: "Queen Anne, Seattle",
    address: "2617 2nd Ave N, Seattle, WA 98109",
    description: "Overgrown drug den restored to period charm 3 story living",
    imgPostUrl: "./images/queen-anne2/01-post.jpg",
    imgB4Url: "./images/queen-anne2/01-b4.jpg",
    mapCoord: "295,408",
    purchaseDate: "Jun-2018",
    purchasePrice: 844061,
    saleDate: "Mar-2019",
    salePrice: 1185000
  },
  {
    propId: 11,
    tag: "kenmore76",
    title: "Kenmore Tri Level Short Plat",
    neighborhood: "Kenmore",
    address: "19519 76th Ave NE, Kenmore, WA 98028",
    description: "Tri-Level Home on Large, Flat Subdividable Parcel",
    imgPostUrl: "./images/kenmore76/01-post.jpg",
    imgB4Url: "./images/kenmore76/01-b4.jpg",
    mapCoord: "462,135",
    purchaseDate: "Jul-2019",
    purchasePrice: 590000,
    saleDate: "N/A",
    salePrice: "N/A"
  }
];
